//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class everydaynews
    {
        public int eid { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string eauthor { get; set; }
        public Nullable<System.DateTime> eupdate { get; set; }
        public string eupdateuser { get; set; }
        public string etitle { get; set; }
        public string edigest { get; set; }
        public string econtent { get; set; }
        public Nullable<int> elook { get; set; }
        public Nullable<int> esay { get; set; }
        public Nullable<int> ewc { get; set; }
        public string state { get; set; }
        public string isvalid { get; set; }
    }
}
